on:
  schedule:
    - cron: '58 21 * * *'
  workflow_dispatch:

jobs:
  Generate_IPv4_ISP:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: BeautifulSoup
      run: |
        pip3 install beautifulsoup4
        rm Generation*
        touch "GenerationTime_v4-$(date)"
        #echo `date` > time.txt
 
    - name: CT
      run: |
        chmod +x ./CT_v6.py
        python3 ./CT_v6.py > cl_ISP_CT_v6.txt
    - name: CU
      run: |
        chmod +x ./CU_v6.py
        python3 ./CU_v6.py > cl_ISP_CU_v6.txt
    - name: CM
      run: |
        chmod +x ./CM_v6.py
        python3 ./CM_v6.py > cl_ISP_CM_v6.txt

    - name: Commit and Push Changes
      id: commit-and-push
      uses: stefanzweifel/git-auto-commit-action@v4
    # - name: Push changes
    #   if: steps.commit.outputs.push == 'true'
    #   uses: ad-m/github-push-action@master
    #   with:
    #      github_token: ${{ secrets.GITHUB_TOKEN }}
